from enum import Enum
class PokemonType(Enum):
    NORMAL   = "normal"
    FIRE     = "fire"
    WATER    = "water"
    GRASS    = "grass"
    ELECTRIC = "electric"
    ICE      = "ice"
    FIGHTING = "fighting"
    POISON   = "poison"
    GROUND   = "ground"
    FLYING   = "flying"
    PSYCHIC  = "psychic"
    BUG      = "bug"
    ROCK     = "rock"
    GHOST    = "ghost"
    DRAGON   = "dragon"
    DARK     = "dark"
    STEEL    = "steel"
    FAIRY    = "fairy"

class AilmentType(Enum):
    NONE = "none"
    PARALYSIS = "paralysis"
    SLEEP = "sleep"
    POISON = "poison"
    BURN = "burn"
    FREEZE = "freeze"
    CONFUSION = "confusion"