from enum import Enum
class PokemonType(Enum):
    NORMAL   = "normal"
    FIRE     = "fire"
    WATER    = "water"
    GRASS    = "grass"
    ELECTRIC = "electric"
    ICE      = "ice"
    FIGHTING = "fighting"
    POISON   = "poison"
    GROUND   = "ground"
    FLYING   = "flying"
    PSYCHIC  = "psychic"
    BUG      = "bug"
    ROCK     = "rock"
    GHOST    = "ghost"
    DRAGON   = "dragon"
    DARK     = "dark"
    STEEL    = "steel"
    FAIRY    = "fairy"


class AilmentType(Enum):
    BURN = "BURN"
    CONFUSION = "CONFUSION"
    FREEZE = "FREEZE"
    LEECH_SEED = "LEECH-SEED"
    NONE = "NONE"
    PARALYSIS = "PARALYSIS"
    POISON = "POISON"
    SILENCE = "SILENCE"
    SLEEP = "SLEEP"
    UNKNOWN = "UNKNOWN"